name: ExamplePluginKotlin
version: '${project.version}'
main: me.andreasmelone.examplepluginkotlin.ExamplePluginKotlin
api-version: '1.19'

commands:
  giveitem:
    permission: exampleplugin.giveitem
  reloadexample:
    permission: exampleplugin.reload

permissions:
  exampleplugin.giveitem:
    description: Allows the player to give himself an item
    default: op
  exampleplugin.reload:
    description: Allows the player to reload the config
    default: op