name: ExamplePlugin
version: '${project.version}'
main: me.andreasmelone.exampleplugin.ExamplePlugin
api-version: '1.19'

commands:
  reloadexample:
    permission: exampleplugin.reload

permissions:
  exampleplugin.reload:
    description: Allows the player to reload the config
    default: op